# Generated by Django 3.2 on 2021-04-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название экскурсии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('duration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность')),
                ('max_people_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кол-во человек')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стоимость')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='excursions_photos', verbose_name='Фото')),
                ('type', models.CharField(choices=[('group', 'Групповая'), ('individual', 'Индивидуальная')], default='group', max_length=10)),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
                'ordering': ['-created_at'],
            },
        ),
    ]
