# Generated by Django 3.2 on 2021-04-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Escursion',
            new_name='Exscursion',
        ),
    ]
