# Generated by Django 3.2 on 2021-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_rename_escursion_exscursion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exscursion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Экскурсию', 'verbose_name_plural': 'Экскурсии'},
        ),
        migrations.AlterField(
            model_name='exscursion',
            name='type',
            field=models.CharField(choices=[('group', 'Групповая'), ('individual', 'Индивидуальная')], default='group', max_length=10, verbose_name='Кол-во человек'),
        ),
    ]
