# Generated by Django 3.2 on 2021-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_auto_20210420_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exscursion',
            name='type',
            field=models.CharField(choices=[('group', 'Групповая'), ('individual', 'Индивидуальная')], default='group', max_length=10, verbose_name='Тип'),
        ),
    ]
